name: ehardcore
version: '${project.version}'
main: be.janjevuk.ehardcore.Main
api-version: '1.20'
authors:
  - JanjeVuk
commands:
  balances:
    aliases:
      - money
    description: "manage basic economy of server"
    permission: balance.use
  menu:
    aliases:
      - m
      - profil
    description: "permet d'ouvrir le menu du joueur"
    permission: menu.open